# docker-compose.yml
version: '3.5'

services:

  # Services
  consignment:
    restart: always
    build: ./shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  user:
    build: ./shippy-service-user
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_BROKER: "nats"
      DB_HOST: "database"
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_NAME: "postgres"

  # Commands
  #  cli:
  #    build: ./shippy-cli-consignment
  #  user-cli:
  #    build: ./shippy-cli-user

  # Database tier
  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432

  event-broker-nats:
    image: nats
    ports:
      - 4222:4222

  rpc-api:
    image: micro/micro:v2.9.3
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
    command:
      - "api"
      - "--handler=rpc"
    ports:
      - 8080-8081:8080-8081
